### ISSUE TITLE
Prompt for updating to the latest version, when I'm already on the latest version

### ISSUE THREAD

**Issue by TEJLJR** [Minh-Ton/openinstallcreator#1]
![Screen Shot 2020-05-05 at 13 28 42](https://user-images.githubusercontent.com/18595589/81096494-72e45900-8ed4-11ea-9474-1e90c073d5ae.png)

When opening the app, I am greeted with this message, even though I downloaded the latest version twice.

**Comment by Minh-Ton** [comment]
That's the problem that I have been trying to fix. You can easily bypass it by turning WiFi off and after that turn in on again and that annoying popup will be removed.

**Comment by minh-ton** [comment]
@TEJLJR I fixed that problem. You can use the app normally again. I apologize for the inconvenience.

**Comment by TEJLJR** [comment]
Thanks. I left a comment on your Volume Icon app as well

**Comment by Minh-Ton** [comment]
Just a side note: _I saw you with an another moderator on the Catalina & Mojave Patcher subreddit. Why don't you add the experts and contributors as moderators?_

**Comment by TEJLJR** [comment]
I still have to do that, but I am not the owner of the Catalina Patcher sub
